---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: ''
  label: Pages
  create: all
  match: "**/*"
  templates:
  - page-4
  - page-3
  - page-1
  - page-2
- type: directory
  path: pages-with-modules
  label: Pages w/ modules
  create: documents
  match: "**/*"
  templates:
  - test-modules
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
